### ISSUE TITLE
Errors following guide

### ISSUE THREAD

**Issue by edorguez** [amh1979/Reporting#14]
I have been searching for a library documentation but I only could get just one guide and I'm having some problems with it. I'm trying to show a report to the user using a RDLC file.

The guide is on the following link: [Integrating RDLC reports to .NET Core Projects](http://blog.geveo.com/IntegratingRDLCReportsToNetCoreProjects).

By the moment here is my current code and the place where I am getting errors:

![code](https://user-images.githubusercontent.com/30707274/91609313-ffa39e80-e92b-11ea-874e-38dd8b84524c.png)

_Project Type: ASP NET Core Web Application MVC.
Net Core Version: 3.1.
IDE: Visual Studio 2019._

### **1. Error formatting file paths**
On the guide they use the following code to format the path
`string fileDirPath = Assembly.GetExecutingAssembly().Location.Replace("ReportAPI.dll", string.Empty);`
`string rdlcFilePath = string.Format("{0}ReportFiles\\{1}.rdlc", fileDirPath, reportName);` 

That means the path would be like this.. 
`C:\Users\...\ReportNetCore3\bin\Debug\netcoreapp3.1\ReportNetCore3.dllReportFiles\UserDetails.rdlc`.

Throwing a **System.IO.FileNotFoundException**. But it can be solved writting the direct link like this.. 
`string rdlcFilePath = C:\Users\...\bin\Debug\netcoreapp3.1\ReportFiles\UserDetails.rdlc`

### **2. Error due to definition of the report**
Finally, when everything before is working, I am not able to make this final line working.
`var result = report.Execute(RenderType.Pdf, 1, parameters);`

It looks like any change i made it always will throw **AspNetCore.Reporting.LocalProcessingException**

More details about this error below.. Thanks.

> AspNetCore.Reporting.LocalProcessingException
>   HResult=0x80131500
>   Message=An error occurred during local report processing.;The definition of the report 'C:\Users\ ...\bin\Debug\netcoreapp3.1\ReportFiles\UserDetails.rdlc' is invalid.
> An unexpected error occurred in Report Processing.
> Could not load file or assembly 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
>   Source=AspNetCore.ReportingServices
>   StackTrace:
>    at AspNetCore.Reporting.InternalLocalReport.EnsureExecutionSession()
>    at AspNetCore.Reporting.InternalLocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings)
>    at AspNetCore.Reporting.InternalLocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
>    at AspNetCore.Reporting.InternalLocalReport.Render(String format, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
>    at AspNetCore.Reporting.LocalReport.Execute(RenderType renderType, Int32 pageIndex, Dictionary`2 parameters, String findString)
>    at ReportNetCore3.Models.ReportService.GenerateReportAsync(String reportName) in C:\Users\ ...\ReportNetCore3\ReportNetCore3\Models\ReportService.cs:line 43
>    at ReportNetCore3.Controllers.ReportController.Get(String reportName) in C:\Users\ ...\ReportNetCore3\ReportNetCore3\Controllers\ReportController.cs:line 22
>    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
> 
> Inner Exception 1:
> DefinitionInvalidException: The definition of the report 'C:\Users\ ...\bin\Debug\netcoreapp3.1\ReportFiles\UserDetails.rdlc' is invalid.
> An unexpected error occurred in Report Processing.
> Could not load file or assembly 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
> 
> Inner Exception 2:
> ReportProcessingException: An unexpected error occurred in Report Processing.
> Could not load file or assembly 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
> 
> Inner Exception 3:
> FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
>

**Comment by edorguez** [comment]
I could fix the second problem by installing two packages. Obviously the guide I've been following along didn't tell you need those package too when you start a new project.

**1. System.CodeDom
2. System.Data.SqlClient**

I'm still having troubles formatting the file paths as I said in the first problem, but It can be solved by writting the direct path.

**Comment by edorguez** [comment]
Problem solved.

**Comment by edihasaj** [comment]
> Problem solved.

You are a life saver man
