### ISSUE TITLE
Sometimes Reports throw that exception 

### ISSUE THREAD

**Issue by mohamed351** [amh1979/Reporting#15]
![image](https://user-images.githubusercontent.com/34129557/110698526-9df9a200-81a2-11eb-836b-9ee74dbdc3a8.png)
some reports throw that exception and if you reload the app it works  i need to fix that kind of error

**Comment by WaleedNaveed** [comment]
@mohamed351 did you mange to resolve the issue ? Can you kindly explain the solution. I am also getting the same error randomly on some reports.

**Comment by MahmoudElderby** [comment]
@mohamed351 any updates on how to fix this kind of errors, I got the same error randomly?

**Comment by bobtab** [comment]
I got the same error?

**Comment by mohamed351** [comment]
I used stimulsoft in my Asp.net core 
, or you can use Fast Report

**Comment by ani00763** [comment]
I'm getting no data to load error. I dont have any data in the dataset. I just want to display the parameter values.

![ReportGenerationError](https://user-images.githubusercontent.com/69315451/132070252-19054a79-4437-4208-822f-62eb7fcd7fc1.JPG)

**Comment by ani00763** [comment]
> I'm getting no data to load error. I dont have any data in the dataset. I just want to display the parameter values.
> 
> ![ReportGenerationError](https://user-images.githubusercontent.com/69315451/132070252-19054a79-4437-4208-822f-62eb7fcd7fc1.JPG)

it got resolved, i missed to add below line.
System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

**Comment by mohamed351** [comment]
I am using stimulsoft report or Fast Report in ASP.NET CORE Projects
