### ISSUE TITLE
Index was outside the bounds of the array in RDLC reports in ASP.NET Core 3.1 MVC using AspNetCore.Reporting

### ISSUE THREAD

**Issue by WaleedNaveed** [amh1979/Reporting#16]
I am working on an ASP.NET Core MVC application. I am using RDLC for reporting purpose. Project has 60+ reports. I am facing a very strange and random issue. I randomly get

`Report can not be generated. An error occurred during local report processing.; An unexpected error occurred in report processing.&#xD;&#xA;Index was outside the bounds of the array. . Try again`

error on reports. After getting this exception, this exception comes on all reports. If i stop the solution and run again then reports work fine but after downloading 3 4 reports, this error again starts coming.

I am stuck and can't find any solution to this. According to solutions available on internet, they ask to clear the cache but i can't find any RDLC cache file in any directory.

How can i clear the cache of RDLC reports ? How the issue can be resolved ? Any help would be much appreciated.

**Comment by rahou25** [comment]
I'm facing the same issue only on 1 report. When I restart IIS everything goes fine until I publish again the solution.

Anyone has a solution ?

**Comment by aryalfianto** [comment]
same issue on 1 report show then the others get Error.

**Comment by waleed-naveed-tkxel** [comment]
> I'm facing the same issue only on 1 report. When I restart IIS everything goes fine until I publish again the solution.
> 
> Anyone has a solution ?

Same issue. Did you find any solution ?

**Comment by miguelangelflores1983** [comment]
> I'm facing the same issue only on 1 report. When I restart IIS everything goes fine until I publish again the solution.
> 
> Anyone has a solution ?

The same Erro any solution?

**Comment by bobtab** [comment]
I have the same error, Any solution Please ?

**Comment by rahou25** [comment]
My current workaround is to use very simple types in the report. So, Where I was using IIF or CHOOSE, I transfered this to the SQL side with CASE ... WHEN and return only values to display on the report side. Since then seems ok.

**Comment by bobtab** [comment]
thanks but in the first call of report it ok i can print report in the second print i have a error AspNetCore.Reporting.LocalProcessingException: 'An error occurred during local report processing.;Index was outside the bounds of the array

**Comment by rahou25** [comment]
Is that the same report ?

Envoyé depuis un mobile
________________________________
De : bobtab ***@***.***>
Envoyé : Tuesday, August 24, 2021 10:45:18 AM
À : amh1979/AspNetCore.Reporting ***@***.***>
Cc : Rahou ***@***.***>; Comment ***@***.***>
Objet : Re: [amh1979/AspNetCore.Reporting] Index was outside the bounds of the array in RDLC reports in ASP.NET Core 3.1 MVC using AspNetCore.Reporting (#16)


thanks but in the first call of report it ok i can print report in the second print i have a error AspNetCore.Reporting.LocalProcessingException: 'An error occurred during local report processing.;Index was outside the bounds of the array

**Comment by rashedmahamud** [comment]
Do not use any expressions, report will fail.
This is limitation of this library

**Comment by ZukrieMohamad** [comment]
> Do not use any expressions, report will fail.
> This is limitation of this library

Already remove all expression which are IIF, SUM, CDBL and other in RDLC report. Still getting same error.
Situation : open 1st report no problem. Then open 2nd report and getting error. 
Error : An error occurred during local report processing.;An unexpected error occurred in Report Processing. Index was outside the bounds of the array.'

**Comment by ZukrieMohamad** [comment]
If you have parameter. Do not pass through dictionary. Pass using Data Source instead of dictionary. You can try remove all parameter pass using dictionary and no more error occur.

**Comment by amanchoudhary2014** [comment]
> Do not use any expressions, report will fail.
> This is limitation of this library

Still getting same error.

**Comment by amanchoudhary2014** [comment]
> If you have parameter. Do not pass through dictionary. Pass using Data Source instead of dictionary. You can try remove all parameter pass using dictionary and no more error occur.

**How to pass parameters using Data Source?**

Help me to solve it. I am searching for solution since last 4 months.
Sometimes it works , some times it throw exception "index was outside the bounds of the array".

**Comment by WaleedNaveed** [comment]
There is an issue of caching with this library. Because of this issue, "Index out of bound" exception is thrown. The work around of this problem is to create a console application and take your report generation logic to that console application. Once the report is generated from this new console application, you can save it in a shared location from where your actual app can access it. You have to run this new console application as a separate process from your main/actual app. In this way, once the report is generated, the process will end and the cache will also be cleared. So, you will never face this issue again.

This solution worked perfectly in my project and I have never faced the "Index out of bound" exception again.

**Comment by Kreituus** [comment]
Sin embargo si es un servicio Api donde lo estoy generando... No aplicaría en mi caso el de consola... En visual studio 2019. Favor su apoyo para borrar ese cache. Muchas gracias

**Comment by ZukrieMohamad** [comment]
> > If you have parameter. Do not pass through dictionary. Pass using Data Source instead of dictionary. You can try remove all parameter pass using dictionary and no more error occur.
> 
> **How to pass parameters using Data Source?**
> 
> Help me to solve it. I am searching for solution since last 4 months.
> Sometimes it works , some times it throw exception "index was outside the bounds of the array".

Passing parameter using DataSource same as you passing list of data for report.
1) localReport.AddDataSource("testDS", parameters); --pass parameter here, from RDLC report get First(fieldName)
**create class for each report parameter
2) Dictionary<string, string> parameters = new Dictionary<string, string>(); --Do not pass parameter here

**Comment by Kreituus** [comment]
> > > Si tiene el parámetro. No pase por el diccionario. Pase usando la fuente de datos en lugar del diccionario. Puede intentar eliminar todos los pases de parámetros utilizando el diccionario y no se producirán más errores.
> > 
> > 
> > **¿Cómo pasar parámetros usando la fuente de datos?**
> > Ayúdame a solucionarlo. Estoy buscando una solución desde los últimos 4 meses. 
> > A veces funciona, otras veces arroja la excepción "el índice estaba fuera de los límites de la matriz".
> 
> Pasando el parámetro usando DataSource lo mismo que pasando la lista de datos para el informe.
> 
> 1. localReport.AddDataSource ("testDS", parámetros); --pase el parámetro aquí, del informe RDLC obtenga First (fieldName) 
>    ** cree la clase para cada parámetro del informe
> 2. Diccionario <cadena, cadena> parámetros = nuevo Diccionario <cadena, cadena> (); - No pase el parámetro aquí

You could give me your help .. I follow with the problem, I did what you said. And nothing commanding my code to give me your help

public static string generarPDF(DataTable consulta, Dictionary<string, string> parameters,string path)
        {
            string datos = string.Empty;
            string mimtype = "";
            int extension = 1;
            try
            {
                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                Encoding.GetEncoding("windows-1252");
                LocalReport localReport = new LocalReport(path);
                localReport.AddDataSource("DataSet1", consulta);
                ReportResult result = localReport.Execute(RenderType.Pdf, extension, parameters: parameters, mimtype);
                byte[] numArray = result.MainStream;
                datos= Convert.ToBase64String(numArray);
                
            }
            catch (Exception)

            {
                throw;
            }
            return datos;
        }

**Comment by lobo-ponto25** [comment]
Forget about it, problems will never be fixed. The solution is here: https://www.nuget.org/packages/ReportViewerCore.NETCore/

**Comment by Dawood-Jamil** [comment]
Can someone please help me with exception "Index was outside the bounds of the array" .A single report works fine in a asp.net core project but while generating another report with parameters is throwing exception. If we generate the other report without parameters it runs but on passing parameters it throws exception. I have been looking for solution for days.

**Comment by Dawood-Jamil** [comment]
@WaleedNaveed Can u help with sample code.. How we can generate rdlc report using windows console

**Comment by Dawood-Jamil** [comment]
Finally I found the solution, the main problem is passing extension as 1.

Just Don't Pass extension as 1 in : 

 var result = localReport.Execute(RenderType.Pdf, ext, param);

This is how I solved this:

   int ext = (int)(DateTime.Now.Ticks >> 10);
    var result = localReport.Execute(RenderType.Pdf, ext, param);

In other words, extension should not be same for every report.

**Comment by Naweap** [comment]
> Finally I found the solution, the main problem is passing extension as 1.
> 
> Just Don't Pass extension as 1 in :
> 
> var result = localReport.Execute(RenderType.Pdf, ext, param);
> 
> This is how I solved this:
> 
> int ext = (int)(DateTime.Now.Ticks >> 10); var result = localReport.Execute(RenderType.Pdf, ext, param);
> 
> In other words, extension should not be same for every report.

When you say "the main problem is passing extension as 1", you mean passing pageIndex as 1. Because next you seems to calculate this value randomly to make it unique. So I think you're talking about pageIndex parameter name.

Btw I'm glad this solved the issue for you, on my side I still have it.

**Comment by FelixYnfanteCodemera** [comment]
Excellent, that work for me

**Comment by WaleedNaveed** [comment]
This issue is related to cache handling in this library. I have found a work around for that and it is mentioned in the following link.

https://github.com/amh1979/AspNetCore.Reporting/issues/16#issuecomment-922505776

Closing this issue.

**Comment by FelixYnfanteCodemera** [comment]
> > Finally I found the solution, the main problem is passing extension as 1.
> > Just Don't Pass extension as 1 in :
> > var result = localReport.Execute(RenderType.Pdf, ext, param);
> > This is how I solved this:
> > int ext = (int)(DateTime.Now.Ticks >> 10); var result = localReport.Execute(RenderType.Pdf, ext, param);
> > In other words, extension should not be same for every report.
> 
> When you say "the main problem is passing extension as 1", you mean passing pageIndex as 1. Because next you seems to calculate this value randomly to make it unique. So I think you're talking about pageIndex parameter name.
> 
> Btw I'm glad this solved the issue for you, on my side I still have it.

were you able to solve the problem?

**Comment by AbelAlex28** [comment]
> > > > Si tiene el parámetro. No pase por el diccionario. Pase usando la fuente de datos en lugar del diccionario. Puede intentar eliminar todos los pases de parámetros utilizando el diccionario y no se producirán más errores.
> > > 
> > > 
> > > **¿Cómo pasar parámetros usando la fuente de datos?**
> > > Ayúdame a solucionarlo. Estoy buscando una solución desde los últimos 4 meses.
> > > A veces funciona, otras veces arroja la excepción "el índice estaba fuera de los límites de la matriz".
> > 
> > 
> > Pasando el parámetro usando DataSource lo mismo que pasando la lista de datos para el informe.
> > 
> > 1. localReport.AddDataSource ("testDS", parámetros); --pase el parámetro aquí, del informe RDLC obtenga First (fieldName)
> >    ** cree la clase para cada parámetro del informe
> > 2. Diccionario <cadena, cadena> parámetros = nuevo Diccionario <cadena, cadena> (); - No pase el parámetro aquí
> 
> You could give me your help .. I follow with the problem, I did what you said. And nothing commanding my code to give me your help
> 
> public static string generarPDF(DataTable consulta, Dictionary<string, string> parameters,string path) { string datos = string.Empty; string mimtype = ""; int extension = 1; try { Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); Encoding.GetEncoding("windows-1252"); LocalReport localReport = new LocalReport(path); localReport.AddDataSource("DataSet1", consulta); ReportResult result = localReport.Execute(RenderType.Pdf, extension, parameters: parameters, mimtype); byte[] numArray = result.MainStream; datos= Convert.ToBase64String(numArray);
> 
> ```
>         }
>         catch (Exception)
> 
>         {
>             throw;
>         }
>         return datos;
>     }
> ```

were you able to solve the problem

**Comment by AbelAlex28** [comment]
> > Finally I found the solution, the main problem is passing extension as 1.
> > Just Don't Pass extension as 1 in :
> > var result = localReport.Execute(RenderType.Pdf, ext, param);
> > This is how I solved this:
> > int ext = (int)(DateTime.Now.Ticks >> 10); var result = localReport.Execute(RenderType.Pdf, ext, param);
> > In other words, extension should not be same for every report.
> 
> When you say "the main problem is passing extension as 1", you mean passing pageIndex as 1. Because next you seems to calculate this value randomly to make it unique. So I think you're talking about pageIndex parameter name.
> 
> Btw I'm glad this solved the issue for you, on my side I still have it.

were you able to solve the problem? how?

**Comment by keyliza** [comment]
Someone found the solution? My case I can download one report correctly anytime but other can't. After restarting server, wiping caché, doesn't work.

**Comment by Naweap** [comment]
> Someone found the solution? My case I can download one report correctly anytime but other can't. After restarting server, wiping caché, doesn't work.

Personally, after spending a few days trying to find a solution, I finally migrated to : [https://www.nuget.org/packages/ReportViewerCore.NETCore/](https://www.nuget.org/packages/ReportViewerCore.NETCore/)

After I've noticed the current package has not received any commit during the last three years, I decided to migrate to a new and maintained package.

**Comment by rahou25** [comment]
I finally migrated to Microsoft.Reporting.NETCore

Since then no problem.

more details here https://github.com/lkosson/reportviewercore

**Comment by FelixYnfanteCodemera** [comment]
> Microsoft.Reporting.NETCore

I already has installed this library, but I still have the same issue, what version did you install?

**Comment by keyliza** [comment]
> > Microsoft.Reporting.NETCore
> 
> I already has installed this library, but I still have the same issue, what version did you install?

Personality I use the last version and some moment gives me a few problems with one report but I was wrong. I'll tell my solution: I Checked the carpet report files .RDLC  if files are there when you publish the app, if not go to the project and remove them and add them again and ready... If this is not your problem, please comment what is.

**Comment by FelixYnfanteCodemera** [comment]
> Personality I use the last version and some moment gives me a few problems with one report but I was wrong. I'll tell my solution: I Checked the carpet report files .RDLC if files are there when you publish the app, if not go to the project and remove them and add them again and ready... If this is not your problem, please comment what is.


Didn't work for me, well i have around 7 rdlc files, if i run the application and execute any report that work fine, but when i try to execute another report then throw the following error: AspNetCore.Reporting.LocalProcessingException: An error occurred during local report processing.;An unexpected error occurred in Report Processing.
I have lost several days on this, I would appreciate if you help me with this

**Comment by keyliza** [comment]
> > Personality I use the last version and some moment gives me a few problems with one report but I was wrong. I'll tell my solution: I Checked the carpet report files .RDLC if files are there when you publish the app, if not go to the project and remove them and add them again and ready... If this is not your problem, please comment what is.
> 
> 
> Didn't work for me, well i have areound 7 rdlc files, if i run the application and execute any report that work fine, but when i try to execute another report then throw the following error: AspNetCore.Reporting.LocalProcessingException: An error occurred during local report processing.;An unexpected error occurred in Report Processing.
> I have lost several days on this, I would appreciate if you help me with this
> 

Are you using this library?
https://www.nuget.org/packages/ReportViewerCore.NETCore/

Users haven't problems using it.

**Comment by FelixYnfanteCodemera** [comment]
> > > Personality I use the last version and some moment gives me a few problems with one report but I was wrong. I'll tell my solution: I Checked the carpet report files .RDLC if files are there when you publish the app, if not go to the project and remove them and add them again and ready... If this is not your problem, please comment what is.
> > 
> > 
> > Didn't work for me, well i have areound 7 rdlc files, if i run the application and execute any report that work fine, but when i try to execute another report then throw the following error: AspNetCore.Reporting.LocalProcessingException: An error occurred during local report processing.;An unexpected error occurred in Report Processing.
> > I have lost several days on this, I would appreciate if you help me with this
> 
> Are you using this library? https://www.nuget.org/packages/ReportViewerCore.NETCore/
> 
> Users haven't problems using it.

No, i already have installed the following libraries:

AspNetCore.Reporting 2.1
ReportViewerCore.NETCore 15.1.16
System.Data.SqlClient 4.8.3
System.Drawing.Common 6.0
System.Text.Encoding.CodePages 6.0

By the way, target framework of my project is .Net Core 3.1

**Comment by keyliza** [comment]
> > > > Personality I use the last version and some moment gives me a few problems with one report but I was wrong. I'll tell my solution: I Checked the carpet report files .RDLC if files are there when you publish the app, if not go to the project and remove them and add them again and ready... If this is not your problem, please comment what is.
> > > 
> > > 
> > > Didn't work for me, well i have areound 7 rdlc files, if i run the application and execute any report that work fine, but when i try to execute another report then throw the following error: AspNetCore.Reporting.LocalProcessingException: An error occurred during local report processing.;An unexpected error occurred in Report Processing.
> > > I have lost several days on this, I would appreciate if you help me with this
> > 
> > Are you using this library? https://www.nuget.org/packages/ReportViewerCore.NETCore/
> > 
> > Users haven't problems using it.
> 
> No, i already have installed the following libraries:
> 
> AspNetCore.Reporting 2.1
> ReportViewerCore.NETCore 15.1.16
> System.Data.SqlClient 4.8.3
> System.Drawing.Common 6.0
> System.Text.Encoding.CodePages 6.0
> 
> By the way, target framework of my project is .Net Core 3.1

Don't use AspNetcore.Reporting library because has a bug when you're try to download some reports, that's why this  discussion, you have to use
 https://www.nuget.org/packages/ReportViewerCore.NETCore/ 

It support Net Core 3.1 & 5

**Comment by FelixYnfanteCodemera** [comment]
> > > > > Personality I use the last version and some moment gives me a few problems with one report but I was wrong. I'll tell my solution: I Checked the carpet report files .RDLC if files are there when you publish the app, if not go to the project and remove them and add them again and ready... If this is not your problem, please comment what is.
> > > > 
> > > > 
> > > > Didn't work for me, well i have areound 7 rdlc files, if i run the application and execute any report that work fine, but when i try to execute another report then throw the following error: AspNetCore.Reporting.LocalProcessingException: An error occurred during local report processing.;An unexpected error occurred in Report Processing.
> > > > I have lost several days on this, I would appreciate if you help me with this
> > > 
> > > 
> > > Are you using this library? https://www.nuget.org/packages/ReportViewerCore.NETCore/
> > > Users haven't problems using it.
> > 
> > 
> > No, i already have installed the following libraries:
> > AspNetCore.Reporting 2.1
> > ReportViewerCore.NETCore 15.1.16
> > System.Data.SqlClient 4.8.3
> > System.Drawing.Common 6.0
> > System.Text.Encoding.CodePages 6.0
> > By the way, target framework of my project is .Net Core 3.1
> 
> Don't use AspNetcore.Reporting library because has a bug when you're try to download some reports, that's why this discussion, you have to use https://www.nuget.org/packages/ReportViewerCore.NETCore/
> 
> It support Net Core 3.1 & 5

I forgot delete that package AspNetCore.ReportingServices, that was the problem. finally work fine for me. Thanks a lot!!

**Comment by samberk1** [comment]
For me cleaning the solution and rebuilding in visual studio solved the issue.

**Comment by pohsgen** [comment]
I faced the same problem too. You can work around it by writing the parameters to the database and read it from the database while populating the report instead of passing it as a parameter.

**Comment by Pun-Mengly** [comment]
> Forget about it, problems will never be fixed. The solution is here: https://www.nuget.org/packages/ReportViewerCore.NETCore/

Thank you. My problem was solved.

**Comment by Brayanassign** [comment]
@aryalfianto https://stackdev.space/questions/data-set-one-connection-methodology
